import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

const geistSans = Geist();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
